---
functional:
  - Требование 1
  - Требование 2
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование 4
implicit:
  - Требование 5
  - Требование 6
